# Database stuff

mariadb_admin_home: '/root'
mariadb_admin_user: 'admin'
mariadb_admin_password:
mariadb_admin_hosts: 
  - '127.0.0.1'
  - 'localhost'
  - '172.16.196.%'
  - '%.maas.hpc1.uwc.ac.za'
  - 'master01.maas.hpc1.uwc.ac.za'

mariadb_apt_keyserver: 'hkp://keyserver.ubuntu.com:80'

# Slurm stuff
db_host: master01.maas.hpc1.uwc.ac.za
db_user: "{{ mariadb_admin_user }}"
db_pass: "{{ mariadb_admin_password }}"

slurm_install_dir: /opt/slurm
slurm_drmaa_support: False
slurm_use_shared_fs: False

slurm_mariadb_name: slurm
slurm_mariadb_pass:

slurm_cluster_name: uwc-eresearch

# Munge options
munge_external_key: False
munge_regenerate_key: True

singularity_version: 3.2.0
golang_version: 1.13
golang_install_dir: '/opt/go/{{ golang_version }}'
golang_gopath: /opt/go/packages

# #NFS
# nfs_exports:
#   - "/share/people"
