# download golang repo
- src: gantsign.golang

# download mariadb
- src: https://github.com/tschifftner/ansible-role-mariadb
  version: master
  name: tschifftner.ansible-role-mariadb

# download ansible-singularity
- src: https://github.com/Banshee1221/ansible-role-slurm
  version: master
  name: ansible-role-slurm

# download ansible-singularity
- src: https://github.com/Banshee1221/ansible-role-singularity
  version: master
  name: ansible-role-singularity

# download NFS role
- src: geerlingguy.nfs

# download cluster software roles
- src: https://github.com/uwc-eresearch/ansible-role-cluster
  version: master
  name: ansible-role-cluster

# download prometheus
- src: cloudalchemy.prometheus

# download grafana
- src: cloudalchemy.grafana

# download alertmanager
- src: cloudalchemy.alertmanager

# download node-exporter
- src: cloudalchemy.node-exporter