---
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  tags:
    - always

- hosts: database
  become: True
  tasks:
    - include_role:
        name: tschifftner.ansible-role-mariadb
  tags:
    - database

- hosts: slurm
  become: True
  pre_tasks:
    - name: create a folder for go
      file:
        path: "{{ golang_install_dir }}"
        recurse: yes
  tasks:
    - include_role:
        name: ansible-role-slurm
      tags:
        - slurm-role
    - include_role: 
        name: ansible-role-singularity
    - name: Template out singularity.conf
      template:
        src: "{{ playbook_dir }}/files/singularity/singularity.j2"
        dest: "{{ singularity_install_dir }}/{{ singularity_version }}/etc/singularity/singularity.conf"
      tags:
        - singularity-role
    - include_role:
        name: ansible-role-cluster
      tags:
        - cluster-role
  tags:
    - slurm

- hosts: node_exporter
  become: True
  tasks:
    - include_role:
        name: cloudalchemy.node-exporter
      tags:
        - node-exporter-role
  tags:
    - monitoring
    - node-exporter

# - hosts: slurm-exporter
#   become: True
#   pre_tasks:
#     - name: Install golang dependency for slurm-exporter
#       apt:
#         name: [golang-github-prometheus-client-golang-dev, golang]
#         state: present
#   roles:
#     - stackhpc.ansible-slurm-exporter
#   environment:
#     PATH: "{{ ansible_env.PATH }}:/usr/bin/go"
#     GOPATH: "/opt/go/packages"
#   tags:
#     slurm-exporter

# - hosts: monitoring
#   become: True
#   tasks:
#     - include_role:
#         name: cloudalchemy.alertmanager
#       tags:
#         - alertmanager-role
#     - include_role:
#         name: cloudalchemy.prometheus
#       tags:
#         - prometheus-role
#     - include_role:
#         name: cloudalchemy.grafana
#       tags:
#         - grafana-role
#   tags:
#     - monitoring